[workspace]
members = [
    "actix",
    "actix-async-await",
    "clacks_crypto",
    "clacks_mtproto",
    "clacks_rpc",
    "clacks_tl_codegen",
    "clacks_transport",
    "grpc-rs",
    "haberdasher_rpc",
    "haberdasherd",
    "haberdasher_irc_agent",
    "haberdasher_telegram_agent",
]
