[package]
name = "haberdasher_rpc"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]
edition = "2018"

[dependencies]
futures = "0.1.27"
protobuf = "2.6.2"

[dependencies.grpcio]
version = "0.4.4"
features = ["openssl"]
