[package]
name = "haberdasherd"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]
edition = "2018"

[dependencies]
capnp = "0.9.1"
capnp-rpc = "0.9.0"
futures = "0.1.25"
tokio = "0.1.11"
haberdasher_rpc = { path = "../haberdasher_rpc" }
