[package]
name = "haberdasherd"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
tokio = "0.1.11"
haberdasher_rpc = { path = "../haberdasher_rpc" }
grpcio = "0.4.0"
